# Generated by Django 5.0.4 on 2024-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0002_alter_author_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=100),
        ),
    ]
