# Generated by Django 5.0.4 on 2024-04-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0003_alter_tag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.TextField(),
        ),
    ]
